/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>


extern void GPIOInit(void);
extern void ADC1Init(void);
extern uint16_t ADC1Read(void);
extern void LEDControl(uint16_t sample);

uint16_t sample = 0;

int main(void){
	GPIOInit();
	ADC1Init();
	while(1) {
		sample = ADC1Read();
		LEDControl(sample);
		}
	}
